---
# Configure your freshly installed software
- hosts: all
  roles:
  - role: osxc.repository
    clone_url: https://github.com/syl20bnr/spacemacs
    dest: /Users/{{ ansible_user_id }}/.emacs.d
    ignore_errors: true
  - role: osxc.repository
    clone_url: https://github.com/robbyrussell/oh-my-zsh.git
    dest: /Users/{{ ansible_user_id }}/.oh-my-zsh
    ignore_errors: true
  - role: osxc.repository
    clone_url: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: /Users/{{ ansible_user_id }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
    ignore_errors: true
  - role: osxc.repository
    clone_url: https://github.com/andreimc/scm_breeze.git
    dest: /Users/{{ ansible_user_id }}/.scm_breeze
    ignore_errors: true
  - role: osxc.repository
    clone_url: https://github.com/tmux-plugins/tpm
    dest: /Users/{{ ansible_user_id }}/.tmux/plugins/tpm
    ignore_errors: true
  - role: osxc.repository
    clone_url: https://github.com/andreimc/maximum-awesome.git
    dest: /Users/{{ ansible_user_id }}/.vim
    ignore_errors: true
    links:
    - src: vimrc
      dest: /Users/{{ ansible_user_id }}/.vimrc
    - src: vimrc.bundles
      dest: /Users/{{ ansible_user_id }}/.vimrc.bundles
    - src: tmux.conf
      dest: /Users/{{ ansible_user_id }}/.tmux.conf
  - role: osxc.repository
    clone_url: https://github.com/gmarik/vundle.git
    dest: /Users/{{ ansible_user_id }}/.vim/bundle/Vundle.vim
  post_tasks:
  - copy: src=dotfiles/zshrc dest=/Users/{{ ansible_user_id }}/.zshrc
  - copy: src=dotfiles/spacemacs dest=/Users/{{ ansible_user_id }}/.spacemacs
  - copy: src=dotfiles/jsbeautifyrc dest=/Users/{{ ansible_user_id }}/.jsbeautifyrc
  - copy: src=dotfiles/gemrc dest=/Users/{{ ansible_user_id }}/.gemrc
  - copy: src=dotfiles/vimrc.local dest=/Users/{{ ansible_user_id }}/.vimrc.local
  - copy: src=dotfiles/vimrc.bundles.local dest=/Users/{{ ansible_user_id }}/.vimrc.bundles.local
  - copy: src=dotfiles/tmux.conf.local dest=/Users/{{ ansible_user_id }}/.tmux.conf.local
  - copy: src=dotfiles/eslintrc dest=/Users/{{ ansible_user_id }}/.eslintrc
  - copy: src=dotfiles/tern-config dest=/Users/{{ ansible_user_id }}/.tern-config
  - file: dest=/Users/{{ ansible_user_id }}/.tmuxinator state=directory
  - copy: src=dotfiles/tmuxinator/projects.yml dest=/Users/{{ ansible_user_id }}/.tmuxinator/projects.yml
  - copy: src=dotfiles/tmuxinator/personal.yml dest=/Users/{{ ansible_user_id }}/.tmuxinator/personal.yml
  - copy: src=dotfiles/tmuxinator/go_jora.yml dest=/Users/{{ ansible_user_id }}/.tmuxinator/go_jora.yml
  - shell: dscl localhost -change /Local/Default/Users/{{ ansible_user_id }} UserShell /bin/bash /usr/local/bin/zsh
    ignore_errors: true
    sudo: yes
  - file: dest=/Users/{{ ansible_user_id }}/.lein state=directory
  - copy: src=dotfiles/profiles.clj dest=/Users/{{ ansible_user_id }}/.lein/profiles.clj

- hosts: all
  roles:
  - osxc.common-env
