---
- name: check ruby version
  command: /bin/bash -c -l 'eval "$(rbenv init -)" && rbenv versions'
  register: current_ruby
- name: install ruby
  command: rbenv install {{ ruby.version }}
  when: ruby.version not in current_ruby.stdout
  ignore_errors: true
- name: set ruby global
  command: rbenv global {{ ruby.version }}
  when: ruby.global == true
- name: check installed gems
  command: /bin/bash -c '/Users/{{ ansible_user_id }}/.rbenv/versions/{{ ruby.version }}/bin/gem list'
  register: installed_gems
  ignore_errors: true
- name: install gems
  command: /bin/bash -c '/Users/{{ ansible_user_id }}/.rbenv/versions/{{ ruby.version }}/bin/gem install {{ item }}'
  with_items: ruby.gems
  when: item not in installed_gems.stdout

